//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public int cityID { get; set; }
        public string cityName { get; set; }
        public int stateID { get; set; }
        public string countryID { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
    }
}
