//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public string countryID { get; set; }
        public string countryName { get; set; }
        public string localName { get; set; }
        public string webCode { get; set; }
        public string region { get; set; }
        public string continent { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public double surfaceArea { get; set; }
        public int population { get; set; }
    }
}
