//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentId { get; set; }
        public string studentName { get; set; }
        public Nullable<int> studentAge { get; set; }
        public string studentAddress { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> Standard { get; set; }
        public string Photo { get; set; }
        public string hobby { get; set; }
    
        public virtual StudentClass StudentClass { get; set; }
    }
}
